version: '3'
services:
  nutriaid:
    build: .
    ports:
      - "3000:3000"
      - "3001:3001"
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:3001
      - SOLANA_RPC_URL=https://api.devnet.solana.com
    volumes:
      - .:/app
      - /app/node_modules
      - /app/frontend/node_modules
      - /app/backend/node_modules
      - /app/nutriaid_solana/node_modules