[features]
seeds = false
skip-lint = false

[programs.devnet]
nutriaid_solana = "Bq4QmQrY2Cys6hSVAatYsWTbbrJczFsxVWQYTaUhoX65"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/root/new-keypair.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
